In [1]:
import numpy as np

# MATH OPERATIONS 

In [4]:
A = np.array([43,56,89,14,78,90,16,31,57,91])
B = np.array([72,90,1,4,89,22,13,76,-14,72])

In [6]:
# Addition

print(np.add(A,B))

[115 146  90  18 167 112  29 107  43 163]


In [7]:
# Subtraction

print(np.subtract(A,B))

[-29 -34  88  10 -11  68   3 -45  71  19]


In [8]:
# Multiply

print(np.multiply(A,B))

[3096 5040   89   56 6942 1980  208 2356 -798 6552]


In [10]:
# Division

print(np.divide(A,B))

[ 0.59722222  0.62222222 89.          3.5         0.87640449  4.09090909
  1.23076923  0.40789474 -4.07142857  1.26388889]


In [11]:
# Sqrt using for loop

In [13]:
import math

arr = np.array([78,92,56,8890,71,41])

sqrt = math.sqrt
A = np.array([78])

for i in A:
    print(sqrt(A))

8.831760866327848


In [17]:
sqrt = math.sqrt
A = np.array([92])

for i in A:
    print(sqrt(A))

9.591663046625438


In [18]:
sqrt = math.sqrt
A = np.array([56])

for i in A:
    print(sqrt(A))

7.483314773547883


In [19]:
sqrt = math.sqrt
A = np.array([8890])

for i in A:
    print(sqrt(A))

94.28679653058533


In [20]:
sqrt = math.sqrt
A = np.array([71])

for i in A:
    print(sqrt(A))

8.426149773176359


In [21]:
sqrt = math.sqrt
A = np.array([41])

for i in A:
    print(sqrt(A))

6.4031242374328485


#  Slicing method :


In [53]:
arr = np.array([78,0,89,19,18,39,79,63,-3,84,-32,-89,-42,65,92])

In [24]:
# positive slicing:

print(arr[1:14])

[  0  89  19  18  39  79  63  -3  84 -32 -89 -42  65]


In [25]:
print(arr[5:9])

[39 79 63 -3]


In [27]:
print(arr[:15])

[ 78   0  89  19  18  39  79  63  -3  84 -32 -89 -42  65  92]


In [28]:
print(arr[5:])

[ 39  79  63  -3  84 -32 -89 -42  65  92]


In [29]:
# negative slicing

print(arr[-13:-9])

[89 19 18 39]


In [32]:
print(arr[-12:-8])

[19 18 39 79]


In [39]:
print(arr[-15:])

[ 78   0  89  19  18  39  79  63  -3  84 -32 -89 -42  65  92]


In [37]:
print(arr[:-1])

[ 78   0  89  19  18  39  79  63  -3  84 -32 -89 -42  65]


In [40]:
# step slicing:

arr = np.array([722,18,19,82,27,19,10,20,30,54])
print(arr[0:7:3])

[722  82  10]


In [41]:
print(arr[4:9:5])

[27]


In [42]:
# return from entire elements:

arr = np.array([92,94,2,69,81,15,61,81,14,72])
print(arr[::4])

[92 81 14]


# Slicing method using 2D array:

In [47]:
A = np.array([[71,89,62,56,91],[82,19,62,17,83]])

In [48]:
print(arr[0,2:4])

[62 56]


In [51]:
print(arr[1,-4:-2])

[19 62]


In [52]:
print(arr[0,-5:-2])

[71 89 62]
