In [1]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [4]:
#import numpy
import numpy as np

In [5]:
# finding length of array

arr = np.array([[12,244,3,40,22],
                [23,56,11,78,91],
                [57,769,1,96,81],
                [13,42,77,21,75],
                [81,34,24,92,62]])
len(arr)

5

In [6]:
print(arr.shape)

(5, 5)


In [9]:
# accessing elements form array

arr = np.array([[12,244,3,40,22],
                [23,56,11,78,91],
                [57,769,1,96,81],
                [13,42,77,21,75],
                [81,34,24,92,62]])

print(arr[0,3]) #3rd element in row 1
print(arr[2,0]) #1st element in row 3
print(arr[3,4]) #5th element in row 4

40
57
75


In [16]:
# accessing 3D array

arr = np.array([[[21,32,55,90],[12,45,67,65]],  
                [[31,56,28,57],[46,22,78,90]],
                [[57,20,27,25],[89,22,43,47]],
                [[23,90,92,68],[81,32,30,72]]])

print(arr[3,0,2])

92


In [17]:
print(arr[2,1,1])

22


In [18]:
print(arr[1,1,3])

90


In [19]:
print(arr[2,0,2])

27


In [28]:
#reshaping elements

arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120])
newarr= arr.reshape(12,10)
print(newarr)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]
 [101 102 103 104 105 106 107 108 109 110]
 [111 112 113 114 115 116 117 118 119 120]]


In [33]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120])

newarr = arr.reshape(5,4,6)
print(newarr)

[[[  1   2   3   4   5   6]
  [  7   8   9  10  11  12]
  [ 13  14  15  16  17  18]
  [ 19  20  21  22  23  24]]

 [[ 25  26  27  28  29  30]
  [ 31  32  33  34  35  36]
  [ 37  38  39  40  41  42]
  [ 43  44  45  46  47  48]]

 [[ 49  50  51  52  53  54]
  [ 55  56  57  58  59  60]
  [ 61  62  63  64  65  66]
  [ 67  68  69  70  71  72]]

 [[ 73  74  75  76  77  78]
  [ 79  80  81  82  83  84]
  [ 85  86  87  88  89  90]
  [ 91  92  93  94  95  96]]

 [[ 97  98  99 100 101 102]
  [103 104 105 106 107 108]
  [109 110 111 112 113 114]
  [115 116 117 118 119 120]]]


In [39]:
newarr = arr.reshape(3,2,20)
print(newarr)

[[[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
    18  19  20]
  [ 21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37
    38  39  40]]

 [[ 41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57
    58  59  60]
  [ 61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77
    78  79  80]]

 [[ 81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97
    98  99 100]
  [101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
   118 119 120]]]
